# MinIO Helm Values for K3s
mode: standalone

replicas: 1

persistence:
  enabled: true
  size: 10Gi
  storageClass: "local-path"

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

ingress:
  enabled: true
  ingressClassName: "traefik"
  hosts:
    - minio.local
  console:
    enabled: true
    hosts:
      - minio-console.local

rootUser: "minioadmin"
rootPassword: "minioadmin123"

buckets:
  - name: pydio-data
    policy: none
    purge: false

users:
  - accessKey: pydiouser
    secretKey: pydiosecret123456
    policy: readwrite
